# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_color"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "conversions between common color models "
categories = ["Color Conversion"]
keywords = ["fortran", "hue", "color", "RGB", "HLS"]
homepage = "https://github.com/urbanjost/M_color.git"

[[test]]
name="runTests"
source-dir="test"
main="test_suite_M_color.f90"
[test.dependencies]
M_msg = { git = "https://github.com/urbanjost/M_msg.git" }
