# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_color"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "conversions between common color models "
categories = ["Color Conversion"]
keywords = ["fortran", "hue", "color", "RGB", "HLS"]
homepage = "https://github.com/urbanjost/M_color.git"

[build]

# new
# force module naming rules to avoid collisions with other packages
module-naming = true
# traditional where user can use any module name
#module-naming = false

[install]
library=true

[[test]]
name="runTests"
source-dir="test"
main="test_suite_M_color.f90"
[test.dependencies]
M_framework = { git = "https://github.com/urbanjost/M_framework.git" }
