# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_color"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "conversions between common color models "
categories = ["Color Conversion"]
keywords = ["fortran", "hue", "color", "RGB", "HLS"]
homepage = "https://github.com/urbanjost/M_color.git"
[build]
   auto-executables = true
   auto-tests = true
   auto-examples = true
   # new default with v0.8.0
   # force module naming rules to avoid collisions with other packages
   module-naming = true
   # traditional where user can use any module name
   #module-naming = false

# new section with v0.8.0
[fortran]
   implicit-typing = false
   implicit-external = false
   source-form = "free"
   # traditional pre-version8 compatibility
   #implicit-typing = true
   #implicit-external = true
   #source-form = "default"

[install]
   library=true

[[test]]
   name="runTests"
   source-dir="test"
   main="test_suite_M_color.f90"
   [test.dependencies]
   M_framework = { git = "https://github.com/urbanjost/M_framework.git" }
